#!/bin/bash

##########################################################################
#  simstick-update-stage2 - perform the actual update scripts
#
#  Created: Mon May 30 10:20:36 2016
#  Copyright  2016  Tim Niemueller [www.niemueller.de]
##########################################################################

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Library General Public License for more details.
#
#  Read the full text in the LICENSE.GPL file in the doc directory.

# Assumes $SIMSTICK_UPDATE_PATH to be set by simstick-update (stage 0)

GIT_HASH_OLD=$1
GIT_HASH_NEW=$2

if [[ -z "$GIT_HASH_OLD" || -z "$GIT_HASH_NEW" ]]; then
		echo "FAIL|rcll-simstick-update: failed to determine git hashes"
fi

# Perform update scripts
pushd $SIMSTICK_UPDATE_PATH >/dev/null

if [ ! -d updates.d ]; then
		echo "FAIL|rcll-simstick-update: updates directory not found"
fi

for f in updates.d/*; do
		if [[ "$f" != *"~" ]]; then
				$f || exit $?
		fi
done

echo -e "\n"
echo -e "\033[1;34m *** SimStick update complete. Check log for errors. ***\033[0m"
echo

popd >/dev/null
