#!/bin/bash

##########################################################################
#  simstick-update - base script, invokes stage 1, to be symlinked
#
#  Created: Mon May 30 10:19:30 2016
#  Copyright  2016  Tim Niemueller [www.niemueller.de]
##########################################################################

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Library General Public License for more details.
#
#  Read the full text in the LICENSE.GPL file in the doc directory.

export SIMSTICK_UPDATE_PATH=$(dirname $(readlink -f ${BASH_SOURCE[0]}))

# invoke stage 1
exec "$SIMSTICK_UPDATE_PATH/simstick-update-stage1"
