#!/bin/bash

##########################################################################
#  simstick-update-stage1 - update simtick repo and invoke stage 2
#
#  Created: Mon May 30 10:20:12 2016
#  Copyright  2016  Tim Niemueller [www.niemueller.de]
############################################################################/

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Library General Public License for more details.
#
#  Read the full text in the LICENSE.GPL file in the doc directory.

# Assumes $SIMSTICK_UPDATE_PATH to be set by simstick-update (stage 0)

# Update simstick update repository itself
pushd $SIMSTICK_UPDATE_PATH >/dev/null
source functions.sh

git_repo_check || exit $?

GIT_HASH_OLD=$(git_repo_hash)
git_repo_pull || exit $?
GIT_HASH_NEW=$(git_repo_hash)

echo exec $SIMSTICK_UPDATE_PATH/simstick-update-stage2 $GIT_HASH_OLD $GIT_HASH_NEW

popd >/dev/null
