#!/bin/bash

##########################################################################
#  rebuild - rebuild all relevant packages on the simstick
#
#  Created: Tue Jun 14 09:55:19 2016
#  Copyright  2017  Tim Niemueller
##########################################################################

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Library General Public License for more details.
#
#  Read the full text in the LICENSE.GPL file in the doc directory.

echo "**************************************************************************"
echo
echo "Rebuilding Software"
echo
echo "**************************************************************************"
echo
echo

echo -e "***** Rebuilding Gazebo RCLL *****\n\n"
pushd ~/robotics/gazebo-rcll >/dev/null
make -j4 clean || exit $?
make -j4 all || exit $?
popd >/dev/null

echo -e "***** Rebuilding RCLL Referee Box *****\n\n"
pushd ~/robotics/llsf-refbox >/dev/null
make -j4 clean || exit $?
make -j4 all gui || exit $?
popd >/dev/null

echo -e "***** Rebuilding Fawkes *****\n\n"
pushd ~/robotics/fawkes-robotino >/dev/null
make -j4 clean || exit $?
make -j4 all gui || exit $?
popd >/dev/null


echo "**************************************************************************"
echo
echo "Rebuilding Software DONE"
echo
echo "**************************************************************************"
