#!/bin/bash

##########################################################################
#  simstick-run - run simulation with single robot
#
#  Created: Tue Jun 14 11:29:15 2016
#  Copyright  2016  Tim Niemueller
##########################################################################

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Library General Public License for more details.
#
#  Read the full text in the LICENSE.GPL file in the doc directory.

SIMSTICK_UPDATE_PATH=$(readlink -f $(dirname $(readlink -f ${BASH_SOURCE[0]}))/..)
source $SIMSTICK_UPDATE_PATH/functions.sh

MODE=$1

print_sechead "RUN SIMULATION"

if [ -z "$FAWKES_DIR" ]; then
	print_fail "simstick-run" "FAWKES_DIR not set"
	exit 1
fi

pushd $FAWKES_DIR/bin >/dev/null

echo "Switching to default world for demo mode"
OLD_WORLD=$GAZEBO_WORLD_PATH
export GAZEBO_WORLD_PATH=$GAZEBO_RCLL/worlds/carologistics/llsf-default.world

case $MODE in
	clips)
		echo "Running CLIPS Agent"
		./gazsim.bash -n 3 -t -r -a --team-cyan Carologistics --start-game
		;;
	rosplan-1)
		echo "Running single-robot ROSPlan"
		./gazsim.bash -n 1 -t -r --ros-launch-main rcll_ros:rosplan_production_standalone_rqt.launch --team-cyan Carologistics --start-game
		;;
	*)
		print_fail "simstick-run" "Unknown game configuration to start"
		;;
esac

popd >/dev/null
