#!/bin/bash

##########################################################################
#  simstick-run - run simulation with single robot
#
#  Created: Tue Jun 14 11:29:15 2016
#  Copyright  2016  Tim Niemueller
##########################################################################

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Library General Public License for more details.
#
#  Read the full text in the LICENSE.GPL file in the doc directory.

echo "**************************************************************************"
echo "Running Software with default arguments"
echo "**************************************************************************"
echo

echo "Warnings about unreachable services are normal and expected."
echo "They appear because of running with a smaller number of robots."
echo

pushd ~/robotics/fawkes-robotino/bin >/dev/null
./gazsim.bash -x start -r -n 1 -t -a \
	--ros-launch-main rcll_fawkes_sim:rcll_fawkes_sim_all_1robot.launch
popd >/dev/null

