#!/bin/bash

##########################################################################
#  kill-simulation - kill simulation before performing updates
#
#  Created: Mon May 30 21:57:03 2016
#  Copyright  2016  Tim Niemueller [www.niemueller.de]
##########################################################################

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Library General Public License for more details.
#
#  Read the full text in the LICENSE.GPL file in the doc directory.

# Assumes $SIMSTICK_UPDATE_PATH to be set by simstick-update (stage 0)

source functions.sh

print_sechead "Killing running Simulation"

if [ -z "$FAWKES_DIR" ];  then
	 echo "FAIL|$(basename $0): FAWKES_DIR has not been set as env var"
	 exit 1
fi

echo -n "Checking if simulation is running... "

GAZEBO_PID=$(ps ax | grep "gzclient $GAZEBO_WORLD_FILE" | grep -v grep | cut -f1 -d" ")

if [ -z "$GAZEBO_PID" ]; then
		echo "not running"
else
		echo "running"
		echo "Stopping in $FAWKES_DIR"
		pushd $FAWKES_DIR/bin >/dev/null
		./gazsim.bash -x kill
		popd >/dev/null
fi
