#!/bin/bash

##########################################################################
#  update-fawkes-robotino - update Fawkes robotino with patches
#
#  Created: Mon May 30 21:58:52 2016
#  Copyright  2016  Tim Niemueller [www.niemueller.de]
##########################################################################

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Library General Public License for more details.
#
#  Read the full text in the LICENSE.GPL file in the doc directory.

# Assumes $SIMSTICK_UPDATE_PATH to be set by simstick-update (stage 0)

source functions.sh
print_sechead "Updating Fawkes"

SCRIPT_NAME=$(basename $0)

if [ -z "$FAWKES_DIR" ];  then
	 print_fail "$(basename $0)" "FAWKES_DIR has not been set as env var"
	 exit 1
fi

pushd $FAWKES_DIR >/dev/null

DO_CLEAN=
DO_BUILD=

if compgen -G "$SIMSTICK_UPDATE_PATH/patches.d/fawkes-core-*.patch" > /dev/null; then
		pushd fawkes >/dev/null
		if patch_apply_all $SIMSTICK_UPDATE_PATH/patches.d/fawkes-core-*.patch; then
				DO_BUILD=1
		fi
		if patch_check_needs_clean_all $SIMSTICK_UPDATE_PATH/patches.d/fawkes-core-*.patch; then
				DO_CLEAN=1
		fi
		popd >/dev/null
else
	echo "No relevant patches found for Fawkes Core"
fi

if compgen -G "$SIMSTICK_UPDATE_PATH/patches.d/fawkes-robotino-*.patch" > /dev/null; then
		if patch_apply_all $SIMSTICK_UPDATE_PATH/patches.d/fawkes-robotino-*.patch; then
				DO_BUILD=1
		fi
		if patch_check_needs_clean_all $SIMSTICK_UPDATE_PATH/patches.d/fawkes-robotino-*.patch; then
				DO_CLEAN=1
		fi
else
	echo "No relevant patches found for Fawkes Robotino"
fi

if grep -q "CFLAGS_EXTRA  += -g" etc/buildsys/config.mk; then
	echo
	echo "*** Setting generic code optimization ***"
	echo
	sed -i -e 's/CFLAGS_EXTRA  += -g/CFLAGS_EXTRA += -m64 -mtune=generic -g/g' etc/buildsys/config.mk
	DO_CLEAN=1
	DO_BUILD=1
fi

if [ -n "$DO_CLEAN" ]; then
	echo "Cleaning software tree"
	make -j$(nproc) clean || print_fail "$SCRIPT_NAME" "Failed to clean software"
fi

if [ -n "$DO_BUILD" ]; then
	echo "Building software"
	make -j$(nproc) all gui || print_fail "$SCRIPT_NAME" "Failed to build software"
fi
popd > /dev/null
