#!/bin/bash

##########################################################################
#  update-gazebo-rcll - update Gazebo RCLL repo
#
#  Created: Mon May 30 21:58:52 2016
#  Copyright  2016  Tim Niemueller [www.niemueller.de]
##########################################################################

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Library General Public License for more details.
#
#  Read the full text in the LICENSE.GPL file in the doc directory.

# Assumes $SIMSTICK_UPDATE_PATH to be set by simstick-update (stage 0)

source functions.sh
print_sechead "Updating Gazebo RCLL"

SCRIPT_NAME=$(basename $0)

if [ -z "$GAZEBO_RCLL" ];  then
	 print_fail "$SCRIPT_NAME" "GAZEBO_RCLL has not been set as env var"
	 exit 1
fi

pushd $GAZEBO_RCLL >/dev/null

git_repo_check || exit $?
git_repo_fetch || exit $?
git_repo_pull_cond_build || exit $?

popd > /dev/null
